AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  writeToTable:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-writeTophotoTable
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: writeToTable
      CodeUri: src/writeToTable
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref photoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref photoTable
          TABLE_ARN: !GetAtt photoTable.Arn
          UNSPLASH_ACCESS_KEY: !Ref EnvConfigunsplashaccessKeyAsString
          UNSPLASH_SECRET_KEY: !Ref EnvConfigunsplashsecretKeyAsString
    Metadata:
      StackeryName: writeToTable
  photoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-photoTable
    Metadata:
      StackeryName: photoTable
  sendDailyEmail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-sendDailyEmail
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: sendDailyEmail
      CodeUri: src/sendDailyEmail
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref photoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref photoTable
          TABLE_ARN: !GetAtt photoTable.Arn
    Metadata:
      StackeryName: sendDailyEmail
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfigunsplashaccessKeyAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/unsplash/accessKey
  EnvConfigunsplashsecretKeyAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/unsplash/secretKey
Metadata:
  EnvConfigParameters:
    EnvConfigunsplashaccessKeyAsString: unsplash.accessKey
    EnvConfigunsplashsecretKeyAsString: unsplash.secretKey